apiVersion: apps/v1
kind: Deployment
metadata:
  name: moroz-server
  labels:
    app.kubernetes.io/name: moroz-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: moroz-server
  template:
    metadata:
      name: moroz-server
      labels:
        app.kubernetes.io/name: moroz-server
    spec:
      containers:
        - name: moroz-server
          image: ghcr.io/pmdroid/moroz:latest
          args:
            - /app/moroz
            - --configs=/configs
            - --use-tls=false
            - --debug
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - mountPath: /configs
              name: configs
              readOnly: true
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      volumes:
        - name: configs
          configMap:
            name: moroz-config
            defaultMode: 0440