apiVersion: v1
kind: Service
metadata:
  name: moroz-server
spec:
  selector:
    app.kubernetes.io/name: moroz-server
  ports:
    - protocol: TCP
      port: 8080
      name: http
      targetPort: 8080
  type: ClusterIP
